### ISSUE TITLE
Module 1 4. Big Idea 2. Foundational and Targeted Strategies

### ISSUE THREAD

**Issue by ajp9e** [castl350/STEP#181] opened 2017-08-30 14:25 UTC
I see the pdf link to Foundational Strategies Companion Guide
Is there something for targeted? I know that there are many targeted strategies but I wasn't sure if this is where some summary document of targeted strategies was going?

**Comment by mattsema** [comment] 2017-08-30 15:34
duplicate of #175 closing this issue

**Closed by mattsema** 2017-08-30 15:34 UTC
